server:
  port: 8082
spring:
  application:
    name: customers-app
  datasource:
    url: jdbc:h2:mem:customers
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true