server:
  port: 8084
spring:
  application:
    name: management-app
  datasource:
    url: jdbc:h2:mem:management
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true