CREATE TABLE PURCHASED_PRODUCT
(
    ID            INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    PRODUCT_ID    INT          NOT NULL,
    PRODUCT_NAME  VARCHAR(255) NOT NULL,
    CUSTOMER_ID   INT          NOT NULL,
    QUANTITY      INT          NOT NULL,
    TOTAL_PRICE   FLOAT        NOT NULL,
    PURCHASE_DATE DATE         NOT NULL
);