CREATE TABLE PRODUCT
(
    ID          INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME        VARCHAR(255) NOT NULL,
    CATEGORY    VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR2     NOT NULL
);

CREATE TABLE PRODUCTS_QUANTITY
(
    ID             INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    PRODUCT_ID     INT   NOT NULL,
    QUANTITY       INT   NOT NULL,
    PRICE_PER_ITEM FLOAT NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

CREATE TABLE PURCHASED_PRODUCT
(
    ID          INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    PRODUCT_ID  INT   NOT NULL,
    CUSTOMER_ID INT   NOT NULL,
    QUANTITY    INT   NOT NULL,
    TOTAL_PRICE FLOAT NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
)